In [2]:
import pandas as pd

df = pd.read_csv("./dados_vendas_pe_ce_ba.csv")

# Exibição das primeiras linhas da tabela

In [3]:
df.head()

   ID Estado     Cidade    Categoria  Quantidade  Valor_Venda
0   1     BA   Salvador    Alimentos           4       754.47
1   2     PE     Recife       Roupas           9       147.37
2   3     PE  Petrolina  Eletrônicos           2        80.19
3   4     PE     Recife       Roupas           9       621.92
4   5     PE  Petrolina       Roupas           7       716.26

# Quantidade de linhas e colunas da tabela

In [4]:
df.shape

(30, 6)

# Os tipos de dados de cada coluna

In [5]:
df.dtypes

ID               int64
Estado             str
Cidade             str
Categoria          str
Quantidade       int64
Valor_Venda    float64
dtype: object

# Verificação de existência de valores nulos na tabela

In [6]:
df.isnull().sum()

ID             0
Estado         0
Cidade         0
Categoria      0
Quantidade     0
Valor_Venda    0
dtype: int64

# Verificação de valores duplicados na tabela

In [7]:
df.duplicated().sum()

np.int64(0)

# Estatísticas descritivas

In [8]:
df.describe()

              ID  Quantidade  Valor_Venda
count  30.000000   30.000000    30.000000
mean   15.500000    5.400000   496.509667
std     8.803408    3.012617   282.601654
min     1.000000    1.000000    80.190000
25%     8.250000    3.000000   261.672500
50%    15.500000    6.000000   446.640000
75%    22.750000    7.000000   745.687500
max    30.000000   10.000000   985.960000